apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-management-backend-api.fullname" . }}
data:
  # property-like keys; each key maps to a simple value
  user: {{ .Values.configMap.username }}
  location: {{ .Values.configMap.location }}