# 1. On utilise l'image officielle Node.js (version 22 légère basée sur Alpine Linux)
FROM node:22-alpine

# 2. On crée et on se place dans le dossier de l'application à l'intérieur du conteneur
WORKDIR /app

# 3. On copie uniquement les fichiers de dépendances d'abord
# Cela permet à Docker de mettre en cache l'étape "npm install" si vous ne changez pas vos packages
COPY package*.json ./

# 4. On installe les modules Node.js
RUN npm install

# 5. On copie tout le reste du code de votre application (src, routes, server.js, etc.)
COPY . .

# 6. On définit la variable d'environnement PORT par défaut sur 3000
ENV PORT=3000

# 7. On indique que le conteneur va ouvrir le port 3000
EXPOSE 3000

# 8. La commande pour démarrer votre serveur Node.js
CMD ["npm", "start"]