apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-postgres-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.postgres.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/postgres-data" # 👈 Dossier interne et natif dans Minikube
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgres-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}