pipeline {
    agent any
    environment {
    ENV = 'dev'
    OWNER = 'wahiba'
    }
    stages {
        stage('Hello') {
            steps {
                bat '''
                    @echo off
                    echo Hello from Jenkins!
                    echo Job: %JOB_NAME%
                    echo Build: %BUILD_NUMBER%
                    echo Workspace: %WORKSPACE%
                     echo Owner: %OWNER%
                '''
            }
        }
    }
    
}