pipeline {
    agent any

    tools {
        nodejs "node26"
    }

    environment {
        CI = 'true'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('application/store-management-frontend') {
                    bat 'npm install'
                    bat 'npm run build'
                }
                
            }
        }

       /*  stage('Run Tests') {
            steps {
                sh 'npm run test -- --watch=false --browsers=ChromeHeadless'
            }
        } */

        

        /* stage('Archive Artifacts') {
            steps {
                archiveArtifacts artifacts: '*/dist/*', fingerprint: true
            }
        } */
        stage('Archive Artifacts') {
    steps {
        archiveArtifacts artifacts: 'application/store-management-frontend/dist/**/*', fingerprint: true
    }
}
    }

    post {

        success {
            echo 'Angular application built successfully!'
        }

        failure {
            echo 'Build failed!'
        }

        always {
            cleanWs()
        }
    }
}