apiVersion: v1
kind: Pod
metadata:
  name: pod-use-secret
  namespace: test
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: pod-use-secret-container
    image: nginx
    env:
    - name: PASSWORDONE # Notice that the case is different here
      valueFrom:
        secretKeyRef:
          name: my-secret           # The ConfigMap this value comes from.
          key: key1
    - name: PASSWORDTWO # Notice that the case is different here
      valueFrom:
        secretKeyRef:
          name: my-secret           # The ConfigMap this value comes from.
          key: key2