apiVersion: v1
kind: Service
metadata:
  labels:
    color: green
  name: webapp-pod-nodeport
  namespace: test
spec:
  type: NodePort # Must specify the type else will take clusterIp automatically
  ports:
  - port: 8090 # port where the service listen 
    protocol: TCP
    targetPort: 80 # must equal to containerPort in the pod code in the line 334
    # Optional field
    # By default and for convenience, the Kubernetes control plane
    # will allocate a port from a range (default: 30000-32767)
    nodePort: 30007
  selector:
    color: green # must match   