apiVersion: v1
kind: Service
metadata:
  labels:
    app: courses
  name: courses-service
  namespace: test
spec:
  ports:
  - port: 8090 # port where the service listen 
    protocol: TCP
    targetPort: 80 # must equal to containerPort in the pod code in the line 334
  selector:
    app: courses # must match the pod label in the line 328
  type: ClusterIP # First and default service type
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: home
  name: home-service
  namespace: test
spec:
  ports:
  - port: 8091 # port where the service listen 
    protocol: TCP
    targetPort: 80 # must equal to containerPort in the pod code in the line 334
  selector:
    app: home # must match the pod label in the line 328
  type: ClusterIP # First and default service type
status:
  loadBalancer: {}

---
# Path Based Routing
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
spec:
  ingressClassName: nginx-example # must use one of this list: https://medium.com/@subhampradhan966/understanding-ingress-in-kubernetes-key-concepts-and-configuration-6d5348060598
  rules:
  - http:
      paths:
      - path: /courses
        pathType: Prefix
        backend:
          service:
            name: courses-service
            port:
              number: 8090
      - path: /home
        pathType: Prefix
        backend:
          service:
            name: home-service
            port:
              number: 8091

---
# Host Based Routing
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wildcard-host
spec:
  rules:
  - host: "courses.defence.tn"
    http:
      paths:
      - pathType: Prefix
        path: "/courses"
        backend:
          service:
            name: courses-service
            port:
              number: 8090
  - host: "home.defence.tn"
    http:
      paths:
      - pathType: Prefix
        path: "/home"
        backend:
          service:
            name: home-service
            port:
              number: 8091
